### ISSUE TITLE
ContextMenu support

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#182]
Context-Menus are currently not supported

**Comment by rjahn** [comment]
popup/context menus are now available in repo:

The component gets the property: popupMenu and the menu itself is sent in changed properties -> similar to popup menu button!

There's an additional command: comp/closePopupMenu (requires clientId, componentId)

The close command should be used to notify the server that the popup is closed (async notification is enough)

Test with Browser screen -> right click on label

**Comment by gimmixAT** [comment]
Does the `comp/closePopupMenu` command require the componentId of the Label or Screen? Currently I am trying the label but I get an error:

```
java.lang.IllegalArgumentException: Unsupported componentcom.sibvisions.rad.ui.web.impl.component.WebLabel	at com.sibvisions.rad.server.http.rest.bundle.command.comp.ClosePopupMenu.updateUI(ClosePopupMenu.java:100)	at com.sibvisions.rad.server.http.rest.CommandRouter.process(CommandRouter.java:436)	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:497)	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)	at org.restlet.resource.ServerResource.post(ServerResource.java:1378)	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)	at org.restlet.resource.Finder.handle(Finder.java:236)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Router.doHandle(Router.java:422)	at org.restlet.routing.Router.handle(Router.java:639)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)	at org.restlet.Application.handle(Application.java:385)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Router.doHandle(Router.java:422)	at org.restlet.routing.Router.handle(Router.java:639)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.routing.Router.doHandle(Router.java:422)	at org.restlet.routing.Router.handle(Router.java:639)	at org.restlet.routing.Filter.doHandle(Filter.java:150)	at org.restlet.routing.Filter.handle(Filter.java:197)	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)	at org.restlet.Component.handle(Component.java:408)	at org.restlet.Server.handle(Server.java:507)	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)	at com.sibvisions.rad.server.http.rest.ServerServlet.service(ServerServlet.java:187)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rjahn** [comment]
the componentId of the menu or the menu item

**Comment by rjahn** [comment]
Yes, send the pressButton command. 
If there's no listener on server-side - no response... So this is not wrong. We could add a listener and show a message or something else.

Which screen do you use?
