### ISSUE TITLE
Exception in Tooltip handling

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#399]
Error: Failed to execute 'querySelectorAll' on 'Document': '#' is not a valid selector.
    at Function.find (http://localhost:3000/static/js/bundle.js:234756:43)
    at setEvent (http://localhost:3000/static/js/bundle.js:232315:84)
    at Tooltip.setTargetEventOperations (http://localhost:3000/static/js/bundle.js:232326:13)
    at Tooltip.unloadTargetEvents (http://localhost:3000/static/js/bundle.js:232303:12)
    at Tooltip.componentWillUnmount (http://localhost:3000/static/js/bundle.js:232367:12)
    at callComponentWillUnmountWithTimer (http://localhost:3000/static/js/bundle.js:275325:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:258969:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:259018:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:259078:35)
    at safelyCallComponentWillUnmount (http://localhost:3000/static/js/bundle.js:275332:9)

react-dom.development.js:20085 The above error occurred in the <Tooltip> component:

    at Tooltip (http://localhost:3000/static/js/bundle.js:231852:5)
    at UIPanel (http://localhost:3000/static/js/bundle.js:27977:120)
    at div
    at BorderLayout (http://localhost:3000/static/js/bundle.js:22539:30)
    at Layout (http://localhost:3000/static/js/bundle.js:24839:13)
    at div
    at UIPanel (http://localhost:3000/static/js/bundle.js:27977:120)
    at div
    at BorderLayout (http://localhost:3000/static/js/bundle.js:22539:30)
    at Layout (http://localhost:3000/static/js/bundle.js:24839:13)
    at div
    at UIPanel (http://localhost:3000/static/js/bundle.js:27977:120)
    at div
    at BorderLayout (http://localhost:3000/static/js/bundle.js:22539:30)
    at Layout (http://localhost:3000/static/js/bundle.js:24839:13)
    at div
    at div
    at UIFrame (http://localhost:3000/static/js/bundle.js:20813:104)
    at div
    at UIMobileLauncher (http://localhost:3000/static/js/bundle.js:22380:120)
    at div
    at ResizeHandler (http://localhost:3000/static/js/bundle.js:6202:66)
    at WorkScreen (http://localhost:3000/static/js/bundle.js:7192:66)
    at ScreenManager (http://localhost:3000/static/js/bundle.js:6507:66)
    at ResizeProvider (http://localhost:3000/static/js/bundle.js:39960:20)
    at div
    at div
    at UIManagerFull (http://localhost:3000/static/js/bundle.js:7023:66)
    at Route (http://localhost:3000/static/js/bundle.js:288529:29)
    at Switch (http://localhost:3000/static/js/bundle.js:288731:29)
    at PopupContextProvider (http://localhost:3000/static/js/bundle.js:43653:23)
    at AppWrapper (http://localhost:3000/static/js/bundle.js:82:66)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:283625:37)
    at ReactUI (http://localhost:3000/static/js/bundle.js:722:66)
    at EmbedProvider (http://localhost:3000/static/js/bundle.js:39868:18)
    at TopBar (http://localhost:3000/static/js/bundle.js:34894:23)
    at AppProvider (http://localhost:3000/static/js/bundle.js:39026:74)
    at Router (http://localhost:3000/static/js/bundle.js:288148:30)
    at HashRouter (http://localhost:3000/static/js/bundle.js:286859:35)
    at MiddleMan (http://localhost:3000/static/js/bundle.js:448:31)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

**Comment by rjahn** [comment]
component name was missing
