### ISSUE TITLE
master branch run problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#437]
master branch

npm install
npm start

Browser (http://localhost:3000/) Console:

```
Uncaught ReferenceError: Cannot access 'ProfileMenu' before initialization
    at Module.ProfileMenu (CorporateMenu.tsx:144:1)
    at Module.ProfileMenu (ObjectToString.ts:12:1)
    at registerExportsForReactRefresh (RefreshUtils.js:158:1)
    at Object.executeRuntime (RefreshUtils.js:193:1)
    at $ReactRefreshModuleRuntime$ (moduleIndex.ts:43:1)
    at ./src/moduleIndex.ts (moduleIndex.ts:43:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/main/components/tree/UITreeV2.tsx (TopBar.tsx:222:1)
```

**Comment by rjahn** [comment]
after switching to pr-upgrade branch and back to main, npm install.. the problem was gone?

**Comment by rjahn** [comment]
Problem was a circular dependeny (npm run bundle) -> moduleIndex was imported instead of single files!
