### ISSUE TITLE
open screen again not possible

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#487]
master branch

open Components -> press menu item again -> 

```
TypeError: Cannot read properties of undefined (reading 'data')
    at http://localhost:3000/static/js/bundle.js:14108:50
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:275019:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:276512:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:276484:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:276474:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:276464:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:278347:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:278300:18)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:277517:7)
    at flushSyncCallbacks (http://localhost:3000/static/js/bundle.js:265526:26)
```

**Comment by gimmixAT** [comment]
should be fixed by 3b5c874477c6561ed81089498cc5e8d0bd0c615c
